---
version: "3.7"

services:
  dynamodb:
    image: ${MOTO_NAME}:${MOTO_TAG}
    networks:
      - public
    ports:
      - target: 8000
        published: ${DYNAMODB_PORT:-8000}
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
      replicas: 1
      resources:
        limits:
          cpus: '3'
          memory: 2048M

networks:
  public:
    external: true